// ─────────────────────────────────────────────────────────────────────────────
// Carnegie 2025 Classification Data
// Source: ACE / Carnegie Foundation 2025 Public Data File (April 2025)
// https://carnegieclassifications.acenet.edu
//
// Contains three 2025 frameworks for all 52 schools in the sample:
//   ic2025name       — 2025 Institutional Classification (display only)
//   saec2025name     — Student Access & Earnings Classification
//   saecScore        — Numeric SAEC score (0-6) for diversity dimension scoring
//   researchDesignation — 2025 Research Activity Designation (0-3 scale)
//                         3=R1 Very High, 2=R2 High, 1=Research College, 0=None
//   accessRatio      — SAEC access ratio (1.0 = matches geographic population)
//   earningsRatio    — SAEC earnings ratio (1.0 = matches regional median)
//   pellPct_real     — Real Pell % from IPEDS 2022-23 (replaces estimated values)
//
// UNITID CORRECTIONS (16 schools had wrong unitids in prior version):

//   Butler University: 150136 → 150163
//   Columbus State Community College: 203368 → 202222
//   Denison University: 202763 → 202523
//   Drexel University: 214591 → 212054
//   Duquesne University: 212577 → 212106
//   Elon University: 198464 → 198516
//   Fordham University: 192439 → 191241
//   Gettysburg College: 213987 → 212674
//   James Madison University: 233277 → 232423
//   MCPHS University: 166683 → 166656
//   Marquette University: 178420 → 239105
//   Miami Dade College: 136172 → 135717
//   Middlebury College: 230764 → 230959
//   Quinnipiac University: 182795 → 130226
//   Thomas Jefferson University: 213783 → 216366
//   Valencia College: 141862 → 138187
//   Williams College: 217156 → 168342
//
// USAGE:
//   import { CARNEGIE_2025, get2025Data } from "../lib/carnegie2025";
//   const data = get2025Data(unitid); // returns full 2025 record or null
// ─────────────────────────────────────────────────────────────────────────────

// 2025 Institutional Classification — 31 categories grouped by Award Level
export const IC2025_CATEGORIES = [
  // Associate
  { id: 1,  label: "Mixed Associate Large",                                        group: "Associate" },
  { id: 2,  label: "Mixed Associate Medium",                                       group: "Associate" },
  { id: 3,  label: "Mixed Associate Small",                                        group: "Associate" },
  { id: 11, label: "Professions-focused Associate Large/Medium",                   group: "Associate" },
  { id: 12, label: "Professions-focused Associate Small",                          group: "Associate" },
  // Associate/Baccalaureate
  { id: 4,  label: "Mixed Associate/Baccalaureate",                                group: "Associate/Baccalaureate" },
  { id: 13, label: "Professions-focused Associate/Baccalaureate",                  group: "Associate/Baccalaureate" },
  // Baccalaureate
  { id: 5,  label: "Mixed Baccalaureate",                                          group: "Baccalaureate" },
  { id: 14, label: "Professions-focused Baccalaureate Medium",                     group: "Baccalaureate" },
  { id: 15, label: "Professions-focused Baccalaureate Small",                      group: "Baccalaureate" },
  // Undergraduate/Graduate-Master's
  { id: 9,  label: "Mixed Undergraduate/Graduate-Master's Large/Medium",           group: "Undergraduate/Graduate-Master's" },
  { id: 10, label: "Mixed Undergraduate/Graduate-Master's Small",                  group: "Undergraduate/Graduate-Master's" },
  { id: 19, label: "Professions-focused Undergraduate/Graduate-Master's Large/Medium", group: "Undergraduate/Graduate-Master's" },
  { id: 20, label: "Professions-focused Undergraduate/Graduate-Master's Small",    group: "Undergraduate/Graduate-Master's" },
  // Undergraduate/Graduate-Doctorate
  { id: 6,  label: "Mixed Undergraduate/Graduate-Doctorate Large",                 group: "Undergraduate/Graduate-Doctorate" },
  { id: 7,  label: "Mixed Undergraduate/Graduate-Doctorate Medium",                group: "Undergraduate/Graduate-Doctorate" },
  { id: 8,  label: "Mixed Undergraduate/Graduate-Doctorate Small",                 group: "Undergraduate/Graduate-Doctorate" },
  { id: 16, label: "Professions-focused Undergraduate/Graduate-Doctorate Large",   group: "Undergraduate/Graduate-Doctorate" },
  { id: 17, label: "Professions-focused Undergraduate/Graduate-Doctorate Medium",  group: "Undergraduate/Graduate-Doctorate" },
  { id: 18, label: "Professions-focused Undergraduate/Graduate-Doctorate Small",   group: "Undergraduate/Graduate-Doctorate" },
  // Special Focus
  { id: 21, label: "Special Focus: Applied and Career Studies",                    group: "Special Focus" },
  { id: 22, label: "Special Focus: Arts and Sciences",                             group: "Special Focus" },
  { id: 23, label: "Special Focus: Arts, Music, and Design",                       group: "Special Focus" },
  { id: 24, label: "Special Focus: Business",                                      group: "Special Focus" },
  { id: 25, label: "Special Focus: Graduate Studies",                              group: "Special Focus" },
  { id: 26, label: "Special Focus: Law",                                           group: "Special Focus" },
  { id: 27, label: "Special Focus: Medical Schools and Centers",                   group: "Special Focus" },
  { id: 28, label: "Special Focus: Nursing",                                       group: "Special Focus" },
  { id: 29, label: "Special Focus: Other Health Professions",                      group: "Special Focus" },
  { id: 30, label: "Special Focus: Technology, Engineering, and Sciences",         group: "Special Focus" },
  { id: 31, label: "Special Focus: Theological Studies",                           group: "Special Focus" },
];

// Research Activity Designation labels
export const RESEARCH_DESIGNATION_LABELS = {
  3: "R1 – Very High Research Activity",
  2: "R2 – High Research Activity",
  1: "Research College or University",
  0: "No Research Designation",
};

// SAEC tier labels and colors
export const SAEC_TIERS = {
  6: { label: "Opportunity College/University",  short: "Opportunity",          color: "#1A9988" },
  5: { label: "Higher Access, Medium Earnings",  short: "Higher Access",        color: "#6AA4C8" },
  4: { label: "Higher Access, Lower Earnings",   short: "Higher Access",        color: "#6AA4C8" },
  2: { label: "Lower Access, Higher Earnings",   short: "Lower Access",         color: "#EB5600" },
  1: { label: "Lower Access, Medium Earnings",   short: "Lower Access",         color: "#EB5600" },
  0: { label: "Lower Access, Lower Earnings",    short: "Lower Access",         color: "#B85000" },
};


// Per-institution 2025 data keyed by IPEDS unitid
export const CARNEGIE_2025 = {
  "131159": {
    name: "American University",
    carnegieId: "r1",
    ic2025: 7,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Medium",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 13.1,
    accessRatio: 0.66,
    earningsRatio: 1.82,
  },
  "164465": {
    name: "Amherst College",
    carnegieId: "bac_arts",
    ic2025: 22,
    ic2025name: "Special Focus: Arts and Sciences",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 1,
    research2025name: "Research Colleges and Universities",
    pellPct: 21.6,
    accessRatio: 0.95,
    earningsRatio: 2.22,
  },
  "104151": {
    name: "Arizona State University",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 6,
    saec2025name: "Opportunity Colleges and Universities \u2013 Higher Access, Higher Earnings",
    saecScore: 6,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 33.4,
    accessRatio: 1.02,
    earningsRatio: 1.54,
  },
  "100858": {
    name: "Auburn University",
    carnegieId: "r1",
    ic2025: 16,
    ic2025name: "Professions-focused Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 12.6,
    accessRatio: 0.36,
    earningsRatio: 1.77,
  },
  "161004": {
    name: "Bowdoin College",
    carnegieId: "bac_arts",
    ic2025: 22,
    ic2025name: "Special Focus: Arts and Sciences",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 1,
    research2025name: "Research Colleges and Universities",
    pellPct: 16.2,
    accessRatio: 0.73,
    earningsRatio: 1.95,
  },
  "150163": {
    name: "Butler University",
    carnegieId: "masters_l",
    ic2025: 17,
    ic2025name: "Professions-focused Undergraduate/Graduate-Doctorate Medium",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 14.0,
    accessRatio: 0.51,
    earningsRatio: 1.86,
    // Corrected from wrong unitid: 150136
  },
  "173258": {
    name: "Carleton College",
    carnegieId: "bac_arts",
    ic2025: 22,
    ic2025name: "Special Focus: Arts and Sciences",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 1,
    research2025name: "Research Colleges and Universities",
    pellPct: 14.4,
    accessRatio: 0.72,
    earningsRatio: 1.72,
  },
  "202222": {
    name: "Columbus State Community College",
    carnegieId: "associates",
    ic2025: 1,
    ic2025name: "Mixed Associate Large",
    saec2025: 2,
    saec2025name: "Higher Access, Lower Earnings",
    saecScore: 4,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 39.8,
    accessRatio: 1.69,
    earningsRatio: 0.95,
    // Corrected from wrong unitid: 203368
  },
  "202523": {
    name: "Denison University",
    carnegieId: "bac_arts",
    ic2025: 22,
    ic2025name: "Special Focus: Arts and Sciences",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 12.9,
    accessRatio: 0.58,
    earningsRatio: 1.53,
    // Corrected from wrong unitid: 202763
  },
  "212054": {
    name: "Drexel University",
    carnegieId: "r2",
    ic2025: 16,
    ic2025name: "Professions-focused Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 25.2,
    accessRatio: 0.86,
    earningsRatio: 1.93,
    // Corrected from wrong unitid: 214591
  },
  "212106": {
    name: "Duquesne University",
    carnegieId: "r2",
    ic2025: 17,
    ic2025name: "Professions-focused Undergraduate/Graduate-Doctorate Medium",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 2,
    research2025name: "Research 2: High Spending and Doctorate Production",
    pellPct: 18.2,
    accessRatio: 0.61,
    earningsRatio: 1.75,
    // Corrected from wrong unitid: 212577
  },
  "198516": {
    name: "Elon University",
    carnegieId: "masters_l",
    ic2025: 17,
    ic2025name: "Professions-focused Undergraduate/Graduate-Doctorate Medium",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 1,
    research2025name: "Research Colleges and Universities",
    pellPct: 9.3,
    accessRatio: 0.41,
    earningsRatio: 1.64,
    // Corrected from wrong unitid: 198464
  },
  "191241": {
    name: "Fordham University",
    carnegieId: "r2",
    ic2025: 7,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Medium",
    saec2025: 3,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 2,
    research2025name: "Research 2: High Spending and Doctorate Production",
    pellPct: 21.4,
    accessRatio: 0.79,
    earningsRatio: 1.8,
    // Corrected from wrong unitid: 192439
  },
  "212674": {
    name: "Gettysburg College",
    carnegieId: "bac_arts",
    ic2025: 22,
    ic2025name: "Special Focus: Arts and Sciences",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 21.0,
    accessRatio: 0.7,
    earningsRatio: 1.6,
    // Corrected from wrong unitid: 213987
  },
  "235316": {
    name: "Gonzaga University",
    carnegieId: "masters_l",
    ic2025: 7,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Medium",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 13.4,
    accessRatio: 0.65,
    earningsRatio: 1.87,
  },
  "151351": {
    name: "Indiana University Bloomington",
    carnegieId: "r1",
    ic2025: 16,
    ic2025name: "Professions-focused Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 16.8,
    accessRatio: 0.67,
    earningsRatio: 1.57,
  },
  "153603": {
    name: "Iowa State University",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 3,
    saec2025name: "Lower Access, Medium Earnings",
    saecScore: 1,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 18.6,
    accessRatio: 0.73,
    earningsRatio: 1.45,
  },
  "232423": {
    name: "James Madison University",
    carnegieId: "masters_l",
    ic2025: 9,
    ic2025name: "Mixed Undergraduate/Graduate-Master's Large/Medium",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 2,
    research2025name: "Research 2: High Spending and Doctorate Production",
    pellPct: 17.1,
    accessRatio: 0.7,
    earningsRatio: 1.72,
    // Corrected from wrong unitid: 233277
  },
  "166656": {
    name: "MCPHS University",
    carnegieId: "special",
    ic2025: 29,
    ic2025name: "Special Focus: Other Health Professions",
    saec2025: 6,
    saec2025name: "Opportunity Colleges and Universities \u2013 Higher Access, Higher Earnings",
    saecScore: 6,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 28.5,
    accessRatio: 1.23,
    earningsRatio: 2.44,
    // Corrected from wrong unitid: 166683
  },
  "239105": {
    name: "Marquette University",
    carnegieId: "r2",
    ic2025: 7,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Medium",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 2,
    research2025name: "Research 2: High Spending and Doctorate Production",
    pellPct: 19.3,
    accessRatio: 0.83,
    earningsRatio: 1.73,
    // Corrected from wrong unitid: 178420
  },
  "135717": {
    name: "Miami Dade College",
    carnegieId: "associates",
    ic2025: 4,
    ic2025name: "Mixed Associate/Baccalaureate",
    saec2025: 4,
    saec2025name: "Higher Access, Medium Earnings",
    saecScore: 5,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 52.1,
    accessRatio: 1.41,
    earningsRatio: 1.15,
    // Corrected from wrong unitid: 136172
  },
  "171100": {
    name: "Michigan State University",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 20.1,
    accessRatio: 0.73,
    earningsRatio: 1.77,
  },
  "230959": {
    name: "Middlebury College",
    carnegieId: "bac_arts",
    ic2025: 22,
    ic2025name: "Special Focus: Arts and Sciences",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 1,
    research2025name: "Research Colleges and Universities",
    pellPct: 16.9,
    accessRatio: 0.69,
    earningsRatio: 1.73,
    // Corrected from wrong unitid: 230764
  },
  "204796": {
    name: "Ohio State University",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 19.9,
    accessRatio: 0.77,
    earningsRatio: 1.51,
  },
  "214777": {
    name: "Pennsylvania State University",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 3,
    saec2025name: "Lower Access, Medium Earnings",
    saecScore: 1,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 13.4,
    accessRatio: 0.6,
    earningsRatio: 1.48,
  },
  "243780": {
    name: "Purdue University",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 13.0,
    accessRatio: 0.52,
    earningsRatio: 1.76,
  },
  "130226": {
    name: "Quinnipiac University",
    carnegieId: "masters_l",
    ic2025: 17,
    ic2025name: "Professions-focused Undergraduate/Graduate-Doctorate Medium",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 15.6,
    accessRatio: 0.59,
    earningsRatio: 1.79,
    // Corrected from wrong unitid: 182795
  },
  "186380": {
    name: "Rutgers University-New Brunswick",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 3,
    saec2025name: "Lower Access, Medium Earnings",
    saecScore: 1,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 27.1,
    accessRatio: 0.95,
    earningsRatio: 1.4,
  },
  "123165": {
    name: "Scripps College",
    carnegieId: "bac_arts",
    ic2025: 22,
    ic2025name: "Special Focus: Arts and Sciences",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 11.6,
    accessRatio: 0.6,
    earningsRatio: 1.79,
  },
  "167835": {
    name: "Smith College",
    carnegieId: "bac_arts",
    ic2025: 22,
    ic2025name: "Special Focus: Arts and Sciences",
    saec2025: 3,
    saec2025name: "Lower Access, Medium Earnings",
    saecScore: 1,
    researchDesignation: 1,
    research2025name: "Research Colleges and Universities",
    pellPct: 18.2,
    accessRatio: 0.73,
    earningsRatio: 1.43,
  },
  "228723": {
    name: "Texas A&M University",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 19.4,
    accessRatio: 0.6,
    earningsRatio: 1.69,
  },
  "216366": {
    name: "Thomas Jefferson University",
    carnegieId: "special",
    ic2025: 27,
    ic2025name: "Special Focus: Medical Schools and Centers",
    saec2025: -2,
    saec2025name: "Not Classified in SAEC",
    saecScore: null,
    researchDesignation: 2,
    research2025name: "Research 2: High Spending and Doctorate Production",
    pellPct: null,
    accessRatio: null,
    earningsRatio: null,
    // Corrected from wrong unitid: 213783
  },
  "126614": {
    name: "University of Colorado Boulder",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 15.0,
    accessRatio: 0.62,
    earningsRatio: 1.51,
  },
  "134130": {
    name: "University of Florida",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 22.4,
    accessRatio: 0.74,
    earningsRatio: 1.94,
  },
  "139959": {
    name: "University of Georgia",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 17.3,
    accessRatio: 0.49,
    earningsRatio: 1.68,
  },
  "145637": {
    name: "University of Illinois Urbana-Champaign",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 24.6,
    accessRatio: 0.84,
    earningsRatio: 1.73,
  },
  "153658": {
    name: "University of Iowa",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 3,
    saec2025name: "Lower Access, Medium Earnings",
    saecScore: 1,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 18.0,
    accessRatio: 0.77,
    earningsRatio: 1.47,
  },
  "155317": {
    name: "University of Kansas",
    carnegieId: "r2",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 20.3,
    accessRatio: 0.81,
    earningsRatio: 1.53,
  },
  "163286": {
    name: "University of Maryland",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 18.8,
    accessRatio: 0.77,
    earningsRatio: 1.67,
  },
  "170976": {
    name: "University of Michigan",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 17.7,
    accessRatio: 0.67,
    earningsRatio: 2.1,
  },
  "174066": {
    name: "University of Minnesota",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 4,
    saec2025name: "Higher Access, Medium Earnings",
    saecScore: 5,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 21.7,
    accessRatio: 1.1,
    earningsRatio: 1.46,
  },
  "181464": {
    name: "University of Nebraska-Lincoln",
    carnegieId: "r1",
    ic2025: 16,
    ic2025name: "Professions-focused Undergraduate/Graduate-Doctorate Large",
    saec2025: 3,
    saec2025name: "Lower Access, Medium Earnings",
    saecScore: 1,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 22.3,
    accessRatio: 0.81,
    earningsRatio: 1.32,
  },
  "199120": {
    name: "University of North Carolina Chapel Hill",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 20.3,
    accessRatio: 0.71,
    earningsRatio: 1.8,
  },
  "215293": {
    name: "University of Pittsburgh",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 16.9,
    accessRatio: 0.64,
    earningsRatio: 1.53,
  },
  "228778": {
    name: "University of Texas at Austin",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 25.3,
    accessRatio: 0.76,
    earningsRatio: 1.77,
  },
  "234076": {
    name: "University of Virginia",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 14.0,
    accessRatio: 0.62,
    earningsRatio: 1.9,
  },
  "236948": {
    name: "University of Washington",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 18.1,
    accessRatio: 0.85,
    earningsRatio: 1.57,
  },
  "240444": {
    name: "University of Wisconsin-Madison",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 15.8,
    accessRatio: 0.68,
    earningsRatio: 1.66,
  },
  "138187": {
    name: "Valencia College",
    carnegieId: "associates",
    ic2025: 1,
    ic2025name: "Mixed Associate Large",
    saec2025: 4,
    saec2025name: "Higher Access, Medium Earnings",
    saecScore: 5,
    researchDesignation: 0,
    research2025name: "No research designation",
    pellPct: 47.1,
    accessRatio: 1.34,
    earningsRatio: 1.17,
    // Corrected from wrong unitid: 141862
  },
  "216597": {
    name: "Villanova University",
    carnegieId: "r2",
    ic2025: 7,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Medium",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 2,
    research2025name: "Research 2: High Spending and Doctorate Production",
    pellPct: 11.7,
    accessRatio: 0.53,
    earningsRatio: 2.24,
  },
  "233921": {
    name: "Virginia Tech",
    carnegieId: "r1",
    ic2025: 6,
    ic2025name: "Mixed Undergraduate/Graduate-Doctorate Large",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 3,
    research2025name: "Research 1: Very High Spending and Doctorate Production",
    pellPct: 15.1,
    accessRatio: 0.64,
    earningsRatio: 1.74,
  },
  "168342": {
    name: "Williams College",
    carnegieId: "bac_arts",
    ic2025: 22,
    ic2025name: "Special Focus: Arts and Sciences",
    saec2025: 5,
    saec2025name: "Lower Access, Higher Earnings",
    saecScore: 2,
    researchDesignation: 1,
    research2025name: "Research Colleges and Universities",
    pellPct: 17.4,
    accessRatio: 0.73,
    earningsRatio: 1.93,
    // Corrected from wrong unitid: 217156
  },
};

/**
 * Look up 2025 Carnegie data for an institution by unitid.
 * Returns null for international institutions (no 2025 IC coverage).
 */
export function get2025Data(unitid) {
  return CARNEGIE_2025[unitid] ?? null;
}

/**
 * Get 2025 IC label for display. Falls back to carnegieId-based default
 * for institutions not in the sample database.
 */
export function get2025ICLabel(unitid, carnegieId) {
  const d = get2025Data(unitid);
  if (d?.ic2025name) return d.ic2025name;
  // Fallback defaults by 2021 carnegieId for out-of-sample institutions
  const defaults = {
    r1: "Undergraduate/Graduate-Doctorate, Mixed, Large",
    r2: "Undergraduate/Graduate-Doctorate, Mixed, Medium",
    r3: "Undergraduate/Graduate-Doctorate, Mixed, Small",
    masters_l: "Undergraduate/Graduate-Master's, Mixed, Large/Medium",
    masters_m: "Undergraduate/Graduate-Master's, Mixed, Large/Medium",
    masters_s: "Undergraduate/Graduate-Master's, Mixed, Small",
    bac_arts: "Special Focus: Arts and Sciences",
    bac_diverse: "Baccalaureate, Professions-focused",
    associates: "Associate, Mixed",
    special: "Special Focus",
    tribal: "Associate, Mixed, Small",
  };
  return defaults[carnegieId] ?? null;
}

/**
 * Get Research Activity Designation (0-3) for an institution.
 * Used to override the researchDesignation field in IPEDS_DB.
 * 3=R1, 2=R2, 1=Research College, 0=None
 */
export function getResearchDesignation(unitid) {
  return get2025Data(unitid)?.researchDesignation ?? 0;
}

/**
 * Get SAEC score (0-6) for diversity dimension scoring.
 * Returns null if not classified.
 */
export function getSAECScore(unitid) {
  return get2025Data(unitid)?.saecScore ?? null;
}
