// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search_institutions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_institutions_default = defineTool({
  name: "search_institutions",
  title: "Search institutions",
  description: "Search higher-ed institutions by name (case-insensitive). Returns up to 25 matches with core identity fields.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Substring to match against institution name."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("institutions").select(
      "unitid,name,city,state,sector,carnegie_id,research2025name,ic2025group,enrollment"
    ).ilike("name", `%${query}%`).limit(limit ?? 25);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_institution.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_institution_default = defineTool2({
  name: "get_institution",
  title: "Get institution profile",
  description: "Fetch the full institutional profile (identity, flags, rankings, metrics, finance) for a single UNITID.",
  inputSchema: {
    unitid: z2.string().trim().min(1).describe("IPEDS UNITID of the institution.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unitid }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser2(ctx).from("institutions").select("*").eq("unitid", unitid).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: `No institution found for UNITID ${unitid}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { institution: data }
    };
  }
});

// src/lib/mcp/tools/list_r1_institutions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_r1_institutions_default = defineTool3({
  name: "list_r1_institutions",
  title: "List R1 institutions",
  description: "List Carnegie R1 (Research 1) doctoral universities with core identity fields. Optionally filter by state.",
  inputSchema: {
    state: z3.string().trim().length(2).optional().describe("Two-letter state code, e.g. 'CA'."),
    limit: z3.number().int().min(1).max(300).optional().describe("Max rows (default 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ state, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser3(ctx).from("institutions").select("unitid,name,city,state,sector,enrollment,research2025name").eq("research2025", 1).order("name", { ascending: true }).limit(limit ?? 200);
    if (state) q = q.eq("state", state.toUpperCase());
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mfzjsjovbexwleqhrugl";
var mcp_default = defineMcp({
  name: "higher-ed-brand-index-mcp",
  title: "Higher Ed Brand Index",
  version: "0.1.0",
  instructions: "Tools for exploring the mcfadden+co Higher Ed Brand Index dataset of U.S. colleges and universities. Use `search_institutions` to find schools by name, `list_r1_institutions` to enumerate Carnegie R1 doctoral universities, and `get_institution` to fetch a full profile (identity, flags, rankings, metrics, finance) by UNITID.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_institutions_default, get_institution_default, list_r1_institutions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
